name: p1
channels:
  - conda-forge
dependencies:
  - pip
  - setuptools
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - python-dotenv>=0.5.1
  - python=3
  - pytorch
  - torchvision
  - ipython

